<?php
$maat = [
    'Suomi',
    'Belgia',
    'Englanti',
    'Ruotsi',
    'Saksa',
    'Ranska',
    'Hollanti',
    'Espanja',
    'Kreikka',
    'Etelä-Afrikka',
    'Kanada',
    'Skotlanti',
    'Itävalta',
    'Yhdysvallat',
    'Irlanti',
    'Puerto Rico',
    'Alkuperämaa vaihtelee',
    'Viro',
    'Tanska',
    'Italia',
    'Barbados',
    'Portugali',
    'Argentiina',
    'Unkari',
    'Australia',
    'Chile',
    'Bulgaria',
    'Luxemburg',
    'Meksiko',
    'Tsekki',
    'Kuuba',
    'Panama',
    'Islanti',
    'Guatemala',
    'Norja',
    'Guyana',
    'Latvia',
    'Japani',
    'Muu alkuperämaa',
    'Puola',
    'Venäjä',
    'Peru',
    'Liettua',
    'Mauritius',
    'Trinidad ja Tobago',
    'Jamaika',
    'Dominikaaninen tasavalta',
    'Turkki',
    'Nicaragua',
    'Venezuela',
    'Intia',
    'Bermuda',
    'Moldova',
    'Martinique',
    'Georgia',
    'Sveitsi',
    'Etelä-Korea',
    'Kypros',
    'Libanon',
    'Uusi-Seelanti',
    'Slovakia',
    'Montenegro',
    'Kiina',
    'Kroatia',
    'Uruguay',
    'Romania',
    'Armenia',
    'Bolivia',
    'Slovenia',
    'Brasilia',
    'Wales',
    'Thaimaa',
    'Israel',
    'Vietnam',
    'Euroopan unioni',
    'Bahamasaaret',
    'Grenada'
];

$kategoriat = [
  'juomasekoitukset',
  'oluet',
  'lahja- ja juomatarvikkeet',
  'vodkat ja viinat',
  'Ginit ja maustetut viinat',
  'Brandyt, Armanjakit ja Calvadosit',
  'konjakit',
  'viskit',
  'rommit',
  'Liköörit ja Katkerot',
  'Jälkiruokaviinit, väkevöidyt ja muut viinit',
  'punaviinit',
  'valkoviinit',
  'roseeviinit',
  'kuohuviinit & samppanjat',
  'siiderit',
  'alkoholittomat'
];
sort($maat);
sort($kategoriat);
?>